services:
  ollama:
    image: cuenca23/ollama4home-ollama:latest
    volumes: 
      - /ollama 
    ports:
      - ${OLLAMA_WEBAPI_PORT-11434}:11434
  interfaz-ollama:
    volumes: 
      - /ollama 
    image: cuenca23/ollama4home-ui:latest
    build:
      args:
        OLLAMA_BASE_URL: '/ollama'
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  ollama: {}
  open-webui: {}